require "capybara/dsl"
require "capybarel/config"
require "capybarel/version"
require "capybarel/dsl/elements"
require "capybarel/dsl/javascript"
require "capybarel/dsl/from_yaml"
require "capybarel/dsl/all"
